### ISSUE TITLE
made new repo

### ISSUE THREAD

**Issue by PRitt842** [PRitt842/CADeltav2#1]
I ran into endless errors and decided to start over with a new repository. The nc file size is too big and even the txt version of it that I have is over 100MB, so I might have to just use other data (precip, wind, etc) unless I can find a way to reduce it by geography before bringing it into this project. Until I find the way to do reduce the filed size, I'll keep playing around with the other data.

**Comment by KaiZhuPhD** [comment]
You can git ignore the large files (Google search how to do it).
