### ISSUE TITLE
shapefile question

### ISSUE THREAD

**Issue by PRitt842** [PRitt842/CADeltav2#2]
When I use a shapefile in r, do I really only need the .shp file or do I need the whole suite of files including .prj like I am used to needing in ArcMap?

**Comment by KaiZhuPhD** [comment]
You need a bunch of files like in ArcGIS. Use the `sf` package to read shapefiles.
https://datacarpentry.org/r-raster-vector-geospatial/06-vector-open-shapefile-in-r/
